# -*- coding: utf-8 -*-
"""Untitled19.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KU66wrx2RQJMaRDDQ2LZ63trIZD4Espq
"""

# Streamlit Fitness Recommendation System

import streamlit as st

# Define the recommendation function
def get_fitness_recommendation(age, gender, weight, goal, fitness_level, duration):
    """
    Function to recommend fitness plans based on user input.
    """
    if goal.lower() == "weight loss":
        if fitness_level.lower() == "beginner":
            return f"Recommended Plan: Start with brisk walking for {duration} minutes daily, light yoga, and avoid sugary foods."
        elif fitness_level.lower() == "intermediate":
            return f"Recommended Plan: Combine cardio (e.g., running) for {duration} minutes and bodyweight exercises like squats and push-ups."
        elif fitness_level.lower() == "advanced":
            return f"Recommended Plan: High-Intensity Interval Training (HIIT) for {duration} minutes and strength training twice a week."

    elif goal.lower() == "muscle gain":
        if fitness_level.lower() == "beginner":
            return f"Recommended Plan: Start with resistance bands or light weights for {duration} minutes, focusing on form and consistency."
        elif fitness_level.lower() == "intermediate":
            return f"Recommended Plan: Use moderate weights for compound exercises like bench presses and deadlifts. Include 2-3 sets of 8-12 reps."
        elif fitness_level.lower() == "advanced":
            return f"Recommended Plan: Perform heavy strength training with a focus on progressive overload. Split your workout into muscle groups."

    elif goal.lower() == "endurance":
        if fitness_level.lower() == "beginner":
            return f"Recommended Plan: Walk or jog for {duration} minutes daily and include light stretching."
        elif fitness_level.lower() == "intermediate":
            return f"Recommended Plan: Run or cycle for {duration} minutes, gradually increasing the intensity each week."
        elif fitness_level.lower() == "advanced":
            return f"Recommended Plan: Long-distance running, cycling, or swimming for endurance. Include hill sprints to boost performance."

    else:
        return "Invalid goal. Please choose between 'Weight Loss', 'Muscle Gain', or 'Endurance'."

# Streamlit app interface
st.title("Fitness Recommendation System")

st.write("Enter your details below to get personalized fitness recommendations.")

# User inputs
age = st.number_input("Enter your Age:", min_value=1, max_value=120, step=1)
gender = st.radio("Select your Gender:", ["Male", "Female"])
weight = st.number_input("Enter your Weight (kg):", min_value=10, max_value=300, step=1)
goal = st.selectbox("Select your Fitness Goal:", ["Weight Loss", "Muscle Gain", "Endurance"])
fitness_level = st.selectbox("Select your Fitness Level:", ["Beginner", "Intermediate", "Advanced"])
duration = st.slider("Select Workout Duration (minutes):", min_value=10, max_value=120, step=5)

# Recommendation button
if st.button("Get Recommendation"):
    recommendation = get_fitness_recommendation(age, gender, weight, goal, fitness_level, duration)
    st.success(f"💡 {recommendation}")